#---------------------------------#
#      general configuration      #
#---------------------------------#

# linux image
image: ubuntu

# appveyor build version format
version: "{build}"

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Scripts that are called at very beginning, before repo cloning
#init:

# Scripts that run after cloning repository
install:
  - export LATEST_RELEASE_NAME=$(git describe --tags --abbrev=0 --match v*.*.*)
  - echo $LATEST_RELEASE_NAME

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x86 # 32-bit 

# Set environment configuration, https://www.appveyor.com/docs/build-environment/#python
environment:
  QTDIR: C:\Qt\5.9\mingw53_32
  QTIFWDIR: C:\Qt\QtIFW-3.0.1
  PYTHONDIR: C:\Python36
  RELEASE_DIR: $(APPVEYOR_BUILD_FOLDER)\..\Build\%CONFIGURATION%
  INSTALLER_DIR: $(RELEASE_DIR)\..\Installer
  INSTALLER: $(INSTALLER_DIR)\%APPVEYOR_PROJECT_NAME%Installer
  INSTALLER_EXE: $(INSTALLER).exe
  INSTALLER_ZIP: $(INSTALLER)-windows32.zip
  REPO: $(INSTALLER_DIR)\%APPVEYOR_REPO_BRANCH%
  SCRIPTS_DIR: $(APPVEYOR_BUILD_FOLDER)\Scripts
  FTP_DOMAIN: sazonov.org
  FTP_RELEASES_DIR: davinci.sazonov.org/releases
  FTP_REPOS_DIR: davinci.sazonov.org/repositories/%APPVEYOR_REPO_BRANCH%
  FTP_USER:
    secure: Ag6W1J98FaP5sNtcmxvlAg==
  FTP_PASSWORD:
    secure: LiqyRhdTXjYm5IgchOLjKA==

#---------------------------------#
#       build configuration       #
#---------------------------------#

# Branches to build
branches:
  only:
    - linux_gcc

# Build Configuration, i.e. Debug, Release, etc.
configuration:
  - release
  #- debug

# Set paths, etc.
before_build:
  - echo $LATEST_RELEASE_NAME
  - echo $FTP_REPOS_DIR
  - echo %LATEST_RELEASE_NAME%
  - call "%QTDIR%\bin\qtenv2.bat"
  - set PATH=%QTIFWDIR%\bin;%PATH%
  - set PATH=%PYTHONDIR%;%PYTHONDIR%\Scripts;%PATH%
  - pip3 install yattag --quiet
  - pip3 install ftputil --quiet
  - python %SCRIPTS_DIR%\makeQtProFiles.py

# To run your custom scripts instead of automatic MSBuild
build_script:
  - python %SCRIPTS_DIR%\makeBuild.py %APPVEYOR_REPO_BRANCH%

#after_build:

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# To run your custom scripts instead of automatic tests
test_script:
  - call %RELEASE_DIR%\%APPVEYOR_PROJECT_NAME%Console.exe --help
  - call %RELEASE_DIR%\%APPVEYOR_PROJECT_NAME%Tests.exe

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

after_test:
  - python %SCRIPTS_DIR%\makeDeploy.py
  - python %SCRIPTS_DIR%\makeInstaller.py %APPVEYOR_REPO_BRANCH%
  - 7z a -tzip -bso0 -bsp0 %INSTALLER_ZIP% %INSTALLER_EXE%
  - if %CONFIGURATION%==release python %SCRIPTS_DIR%/upload.py %FTP_DOMAIN% %FTP_USER% %FTP_PASSWORD% %REPO% %FTP_REPOS_DIR%
  - if %CONFIGURATION%==release python %SCRIPTS_DIR%/upload.py %FTP_DOMAIN% %FTP_USER% %FTP_PASSWORD% %INSTALLER_ZIP% %FTP_RELEASES_DIR%/%LATEST_RELEASE_NAME%

build: off
