#---------------------------------#
#      general configuration      #
#---------------------------------#

os: linux
#dist: precise # Ubuntu 12.04, https://docs.travis-ci.com/user/reference/overview/
dist: trusty # Ubuntu 14.04, https://docs.travis-ci.com/user/reference/overview/
sudo: required
##group: deprecated-2017Q4 # https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch

compiler: gcc

language: cpp

branches:
  only:
  - linux_gcc

#---------------------------------#
#    environment configuration    #
#---------------------------------#

env:
  # Global variables
  global:
    # ftp user name, password
    - secure: "tl+D0sXQAHVRKMu5cavYWxAMnFTa2tY6yCdktLX/qJ9ymRvyGYj3ygYq/8CWh5LREoBKjqE5Yzo10+YviH3LhmV1IGXGR0X+kycEhKgChkG8D+Sv2KFhOqE3N//xf6s4p/SgCbr7Ln8tNPm3LgnYS1MeIqTw5wylCPQIWdbKggbO91U7OOCC4t7PJ74xL7U0gxrUt1BZ2iHfyhRLEfVMfkDGcC779KSg57Tmb56mPwNL+RArnwQiVgfmmuOsL9aJpx4thPZ8Km8xAyjlVTa42CH+tFuKvTcWCd9i5q3RHToLrHEf1lNjZj5ERmuxXmwkbvNbEbQ6fuKatY9hWyv9BOgaWycN/h2y4aNQumCmx9KRn77REXPtgScicLO/qAxwBYzrG4KOo25BrpFIOcGtFjFrbTV92OjA595Q+nBs5OfoaBpCoVyvwC24mTtyoWG8+A2Pq64iO/o68EaE3XY3Mg7bDM4V7otgY0zzZsLjE0mLHMTg5FGLKfXmp8VY0MSQMa7Y2sp1idbU9cQvjGlDsw+ALrCXF0/4cIPrMWxwv4Aexx/1x7/y3OppVVFWOafiXB2EcjjNL85flXeemv1h97fIRktAa7rQmKLrC1lJQ01vKO3vWH0mcqkPn3knugOM6/s65lzGuNJIvYH2K5Hf9M9DmDvSKnR8gUROLLmQ8/0="
    - secure: "Sx2jwO+oGU5DFhLY2k62hslEBDIkHVna0RVsPRo5Ccy+u9bpZa/Pb4ifY4hzLNe+ggxHpHUrSpXrNOLyp2+rawBWNu09zbrsHzeOH0ib+gZrJaibczc/z0i535p4QAkEWiZcJrc2gcNdc74CT4MB/zcFcsabP2AD4CJjRw36wBJCBN346dPA5EDqI05Yf8ZAhBq3TXkgYF1F2sQrOweF00vJt41dDwqzqpauSjwUGlX+g7IlZ1qYZKnBl+aAVh8XKLhXF07IlXdoS5Z5dz8QeiHNTNTetFTbqDlyhw6mlylXkpCh3ca1booZQwqUhZySG6h4x8VHAm0gJlrHa1HzQyBPMUcMqkK0FHUV6WI9y2E7hgBQ6+6rku1K3UHGYBgyXd2/NYaEsXqBg6GvOatNfyydAvKOzFyzOv7T9RoBwOOIUBAdON1sXh/1gnHb1HxUGFjQGHeV6tqdIWdC+o4h9YbsXENsgxLqevZAM+ekKyv+k+RHpD0uvQbXtW2bd2dBWpoV80+SJHHd/MDtuioGT0enDBbud5NbtljV2qassWVtlO5OWgLchbVZSPZiynDnbwH5jOzqW+7/8smWGfH6z8CpH50z9uvbXepB4ptZLAIlN98cTMUf6bntpVAdWhV6Ehe2OAyQcDcKzoQiZVaOXQYbX9Nn7o0+ssqJtz9Kxgo="
  # Build matrix
  matrix:
    - CONFIGURATION=release
    #- CONFIGURATION=debug

#---------------------------------#
#      install configuration      #
#---------------------------------#

before_install:
  #- python3 --version
  #- sudo apt-get install python3.6
  #- python3 --version
  #- python3.6.3 --version
  # Set variables
  - export BUILD_TYPE="$(tr '[:lower:]' '[:upper:]' <<< ${CONFIGURATION:0:1})${CONFIGURATION:1}"
  # Project
  - export PROJECT_NAME=$(basename ${TRAVIS_REPO_SLUG})
  - export LATEST_RELEASE_NAME=$(git describe --tags --abbrev=0 --match v*.*.*)
  - export SCRIPTS_DIR=${TRAVIS_BUILD_DIR}/Scripts
  - export RELEASE_DIR=${TRAVIS_BUILD_DIR}/../Build/${BUILD_TYPE}
  # Deploy
  - export DEPLOY_DIR=${RELEASE_DIR}/../Deploy
  - export LINUXDEPLOYQT_URL="https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - export LINUXDEPLOYQT_EXE=linuxdeployqt
  - export PATH=$PATH:${TRAVIS_BUILD_DIR}
  # QtIFW
  - export QTIFW_VERSION="3.0.2"
  - export QTIFW_BASE="QtInstallerFramework-linux-x64"
  - export QTIFW_EXE="${QTIFW_BASE}.run"
  - export QTIFW_URL="https://download.qt.io/official_releases/qt-installer-framework/${QTIFW_VERSION}/${QTIFW_EXE}"
  - export QTIFW_SCRIPT="${TRAVIS_BUILD_DIR}/Scripts/silentinstall.js"
  - export PATH=$PATH:~/Qt/QtIFW-${QTIFW_VERSION}/bin
  # Installer
  - export INSTALLER_DIR=${RELEASE_DIR}/../Installer
  - export INSTALLER=${INSTALLER_DIR}/${PROJECT_NAME}Installer
  - export INSTALLER_EXE=${INSTALLER}
  - export INSTALLER_ZIP=${INSTALLER}-linux64.zip
  # Upload
  - export REPO=${INSTALLER_DIR}/${TRAVIS_BRANCH}
  - export FTP_DOMAIN=sazonov.org
  - export FTP_RELEASES_DIR=davinci.sazonov.org/releases
  - export FTP_REPOS_DIR=davinci.sazonov.org/repositories/${TRAVIS_BRANCH}
  # Print variables
  - echo ${CONFIGURATION}
  - echo ${BUILD_TYPE}
  - echo ${TRAVIS_BUILD_DIR}
  - echo ${PROJECT_NAME}
  - echo ${LATEST_RELEASE_NAME}
  - echo ${RELEASE_DIR}
  - echo ${SCRIPTS_DIR}
  - echo ${TRAVIS_BRANCH}
  # Add repositories, update...
  - sudo add-apt-repository --yes ppa:jonathonf/python-3.6
  #- sudo add-apt-repository --yes ppa:deadsnakes/ppa
  - sudo apt-add-repository --yes ppa:beineri/opt-qt592-trusty
  ##- sudo apt-get -qq update
  - sudo apt-get --quiet --yes update
  #-#- sudo apt-get upgrade python

# Install Python, Pip, Qt, QtIFW
install:
  # Python
  - python3 --version
  - sudo apt-get --yes install python3.6
  - python3 --version
  - python3.6 --version
  - curl https://bootstrap.pypa.io/get-pip.py | sudo python3.6
  #- sudo apt-get install python3-pip
  - pip3 --version
  #- sudo rm /usr/bin/python3
  #- sudo ln -s /usr/bin/python3.6 /usr/bin/python3 doesn't really help when run python3
  - sudo pip3 install yattag
  - sudo pip3 install ftputil
  # - sudo python3 -m pip install ftputil EQUALS - sudo apt-get install python3-pip AND - sudo pip3 install ftputil
  #- sudo apt-get --yes install qt59base qt59svg qt59translations qt59webengine
  # Qt
  - sudo apt-get --yes install qt59base qt59svg
  # 7zip
  - sudo apt-get --yes install p7zip-full
  # QtIFW
  - curl -L ${QTIFW_URL} -O
  - chmod a+x ${QTIFW_EXE}
  - QT_QPA_PLATFORM=minimal ${QTIFW_EXE} --script ${QTIFW_SCRIPT} --no-force-installations

####  - python3 ${SCRIPTS_DIR}/upload.py ${FTP_DOMAIN} ${FTP_USER} ${FTP_PASSWORD} /home/travis/build.sh ${FTP_RELEASES_DIR}/${LATEST_RELEASE_NAME}
####  - python3 ${SCRIPTS_DIR}/upload.py ${FTP_DOMAIN} ${FTP_USER} ${FTP_PASSWORD} /home/travis/build.sh ${FTP_RELEASES_DIR}/v1.0.4
  #- ls -l
  #- ls -l /home/
  #- ls -l /home/travis/
  #- ls -l ${INSTALLER_DIR}
####  - ls -l ${SCRIPTS_DIR}
####  - ls -l ${SCRIPTS_DIR}/test
####  - echo ${SCRIPTS_DIR}
####  - echo ${FTP_DOMAIN}
####  - echo ${FTP_USER}
####  - echo ${FTP_RELEASES_DIR}
####  - echo ${LATEST_RELEASE_NAME}
####  - echo ${FTP_REPOS_DIR}
####  - python3.6 ${SCRIPTS_DIR}/upload.py ${FTP_DOMAIN} ${FTP_USER} ${FTP_PASSWORD} ${SCRIPTS_DIR}/test/test.txt ${FTP_RELEASES_DIR}/${LATEST_RELEASE_NAME}
  #- python3.6 ${SCRIPTS_DIR}/upload.py ${FTP_DOMAIN} ${FTP_USER} ${FTP_PASSWORD} ${SCRIPTS_DIR}/test ${FTP_REPOS_DIR}


#---------------------------------#
#       build configuration       #
#---------------------------------#

before_script:
  - source /opt/qt*/bin/qt*-env.sh

script:
  # Build
  - python3.6 ${SCRIPTS_DIR}/makeQtProFiles.py
  - python3.6 ${SCRIPTS_DIR}/makeBuild.py ${TRAVIS_BRANCH}
  #- ls ${RELEASE_DIR}
  # Tests
  - ${RELEASE_DIR}/${PROJECT_NAME}Console --help
  - ${RELEASE_DIR}/${PROJECT_NAME}Tests
  # Deployment, https://github.com/probonopd/linuxdeployqt
  - curl -L ${LINUXDEPLOYQT_URL} -o ${LINUXDEPLOYQT_EXE}
  - chmod a+x ${LINUXDEPLOYQT_EXE}
  - unset QTDIR; unset QT_PLUGIN_PATH; unset LD_LIBRARY_PATH
  - python3.6 ${SCRIPTS_DIR}/makeDeploy.py
####  - ls -l ${DEPLOY_DIR}
  # Installer
  - python3.6 ${SCRIPTS_DIR}/makeInstaller.py ${TRAVIS_BRANCH}
##  - ls -l ${INSTALLER_DIR}
  - 7z a -tzip ${INSTALLER_ZIP} ${INSTALLER_EXE}
##  - ls -l ${INSTALLER_DIR}
##  - ls -l ${DEPLOY_DIR}

#---------------------------------#
#      upload configuration       #
#---------------------------------#
after_success:
##  - echo ${SCRIPTS_DIR}
##  - echo ${FTP_DOMAIN}
##  - echo ${FTP_USER}
##  - echo ${INSTALLER_ZIP}
##  - echo ${FTP_RELEASES_DIR}
##  - echo ${LATEST_RELEASE_NAME}
  #- python3.6 ${SCRIPTS_DIR}/upload.py ${FTP_DOMAIN} ${FTP_USER} ${FTP_PASSWORD} ${REPO} ${FTP_REPOS_DIR};
  - python3.6 ${SCRIPTS_DIR}/upload.py ${FTP_DOMAIN} ${FTP_USER} ${FTP_PASSWORD} ${INSTALLER_ZIP} ${FTP_RELEASES_DIR}/${LATEST_RELEASE_NAME};
  - python3.6 ${SCRIPTS_DIR}/upload.py ${FTP_DOMAIN} ${FTP_USER} ${FTP_PASSWORD} ${REPO} ${FTP_REPOS_DIR};
