#---------------------------------#
#      general configuration      #
#---------------------------------#

os: osx
osx_image: xcode7.3 # OS X 10.11, https://docs.travis-ci.com/user/reference/osx/
#osx_image: xcode8.3 # OS X 10.12, https://docs.travis-ci.com/user/reference/osx/

compiler: clang

language: cpp

branches:
  only:
  - macos_clang

#---------------------------------#
#    environment configuration    #
#---------------------------------#

env:
  # Global variables
  global:
    # FTP_DOMAIN
    - secure: "tYxdTxP7Pm5ubhqgoMcBAk0yaq0V9RtpB+C045F814Mp2g9ERRUfChDKCbrwaCewgQNJBPaWKbBetnEIyNNCWfMsL3jLQrzQ4NVkg0yb7lTiBdlrIea3R6I7QMT6V2aK/wHPPCxY3PoStJ+V8OxZs6mD3OoblZo8GgnHTHIjEdaZWIo5Ay5GNqQk7M6BYFS92uVQ+QB7sM9ukGs5dL0hxHZVmiQKeAM6VayWPQjkcgMRa72E7r1wXWr3tpFuUMcCSkoJVDXEDNshc+Jxo40cHNZP7nGTuFXD5yvI48FYJ5W29ghc5Zw+0YQKdbtSWYvaWP6kblq0fXtJWKksS+xOP+1JLB1+H6R+ZNFAcd0tzmQhMvAMn1lBaRKzebXiMAgOAHZ594MqCml6N90uihyHJqWQUHKzgutVM5DJRrwdDtDRZWuWhgGVdcRcD+d93MxHJX28YmqMSZMtiZmvD0t/qRqsJZNBlB8uiaFHaZW3gZmPjsbAX4YEris3fHCtSVORMex2LPJSZ3/HEhy4ZLwvC5dAtcQzVv09KU2RX38VNN7Xx1oYbbKMnvMeIRa5TBBwFCRilrH9wAvoNHS7AOUNIRG0gQW37zVhQx8s1Mw/4zhSPdRnQvHrv5NGkETQimTEhFs+v6jtLY1ZGx7IXC2xTdAfEVa/YRXLY0sTXTcCg+o="
    # FTP_USER
    - secure: "MH5Wpl/13VVONs9uWRXaK/3fJx6ndZ4Z+ROsNBYcOSbaAKNo5ZgGNSroLIFMOFMcfKxsYwxeA6wG2sQn77guF2V0hpGi4AcQRKXBzbHpoJ+AyD5XnJPMeGIMP1hSxCbVpQPBSYiOomgxDiHJPu9rcOMa6ODmNpPNZdAZQP3DWCwF1TSb7XFxOpU0PHCnMS7KB+AhyRq4N30d+8TJmrkf6A4d+74p98WmEtJdqRub7iI54Xmdnet1i7KRaeUNAGVmq+sppjySwT+jpTy1SN6YsX5BrvvYv0sOljO5lp9HlhiTKFX4BNYJJIzUOjvjAQ5CqCBc2K50SrvhM004s3QdRAXB4Ku6nQ8zdefsD/QG0GQdt0isagnoYcBP3FOOZJhtV13eEkOuC6q+oiyHcJucfrQCrrw2/xby2rpJR3NdIChyodCPMFHNJhHZUuCHnrtNBrIBrvfG9aF4uZtRM+fWUgn9Dh3eM+iYGjJWI1L72l0nNWqwPHiTAT29CL0GkiazId9bQVvDuOodabyhKMdUAhSIbXCk/NrRGLvvA7/5svnVtlf3s5qdsw41jBNbbYwYZ8hw2e2ybIui9DnyXydj/VuEPAYalqlQxI6o+2qHyLTLfhiuB9R8jLJ8xwdI0lESpzZCn/+yn/6qID4xBERqFpiGirOhNbDM1yvu8WLO2tc="
    # FTP_PASSWORD
    - secure: "b75ZnvI4ZNfLgNBE7Btqt2v3tfm6vOTVq/2rkmbkZ2BrfkShPyO7LX8LJqjIIxYIMs7P/PP1DitV6MAZ9HwMjjcjMIkSKG9iOjdk1hCTC+yZfnjKbgQpF9V6B8f2RvqK3u0ta0u5P7RlTJ8OaEKhpoafqp/E0rggZKzPGQKnz7+3hmXAwL/yS51fz+RG7bGPAOwzNI6iR1qqYCJdtjKtweduMNUmUkZYHUUzcp4A1oSCOTpkfBq9BfLQL8OhiX2yxWE0K9msPNARUIjAttNxp00qiF09hX0myjwKfaQIR35SxQK29vdKpfbRDIt0fEQm5eMIrSZDpvQzdu73O6JzML5kaaSFyQtV07wb3afhZ1YcKk3kpFatJVwv8KBNyR7O2X/grCKbOAI3o5umljgX5Dmx7FzH7bv/Te2nMaot9dWDuiKkP8Sr0zJCrLgyNEpXYroTCUvk0IdHxtf1K2lg1csLw3oJfgDNI7xbmkmFs8th878VGWnwu4HYUMEU0fFzcV98gntw3Cc8GbO1jvhf+pDXA6ENP42s/uDEFKvrlRbuzXemrpeX+gNpqeSswicxIw/qnQd5wYdpsxyWRHxczzOvnv+xfGjexu4AsHKM881yE79EjnUPoTYpDTuhqgJh/3kVf8AOwFLU2XaNIjPgVss4ETr/oVx/fxF6ZCOQOu8="
  # Build matrix
  matrix:
    - CONFIGURATION=release
    #- CONFIGURATION=debug

#---------------------------------#
#      install configuration      #
#---------------------------------#

before_install:
  # Set variables
  - export BRANCH=${TRAVIS_BRANCH}
  - export BUILD_DIR=${TRAVIS_BUILD_DIR}
  - export BUILD_TYPE="$(tr '[:lower:]' '[:upper:]' <<< ${CONFIGURATION:0:1})${CONFIGURATION:1}"
  # Project
  - export PROJECT_NAME=$(basename $TRAVIS_REPO_SLUG)
  - export LATEST_RELEASE_NAME=$(git describe --tags --abbrev=0 --match v*.*.*)
  - export SCRIPTS_DIR=${BUILD_DIR}/Scripts
  - export RELEASE_DIR=${BUILD_DIR}/../Build/${BUILD_TYPE}
  # QtIFW
  - export QTIFW_VERSION="3.0.4"
  - export QTIFW_BASE="QtInstallerFramework-mac-x64"
  - export QTIFW_EXE="/Volumes/${QTIFW_BASE}/${QTIFW_BASE}.app/Contents/MacOS/${QTIFW_BASE}"
  - export QTIFW_URL="https://download.qt.io/official_releases/qt-installer-framework/${QTIFW_VERSION}/${QTIFW_BASE}.dmg"
  - export QTIFW_SCRIPT="${BUILD_DIR}/Scripts/silentinstall.js"
  - export PATH=$PATH:~/Qt/QtIFW-${QTIFW_VERSION}/bin
  # Installer
  - export INSTALLER_DIR=${RELEASE_DIR}/../Installer
  - export INSTALLER=${INSTALLER_DIR}/${PROJECT_NAME}Installer
  - export INSTALLER_EXE=${INSTALLER}.app
  - export INSTALLER_ZIP=${INSTALLER}-macos64.zip
  # Upload
  - export REPO=${INSTALLER_DIR}/${BRANCH}
  - export FTP_RELEASES_DIR=releases
  - export FTP_REPOS_DIR=repositories/${BRANCH}
  # Print variables
  - sw_vers # macOS version
  - echo ${BRANCH}
  - echo ${CONFIGURATION}
  - echo ${BUILD_TYPE}
  - echo ${BUILD_DIR}
  - echo ${PROJECT_NAME}
  - echo ${LATEST_RELEASE_NAME}
  - echo ${RELEASE_DIR}
  - echo ${SCRIPTS_DIR}
  # Update...
  - brew update

# Install Python, Pip, Qt, QtIFW
install:
  # Python
  #- brew install python3
  - brew upgrade python # upgrade to python3
  - python3 --version
  - pip3 --version
  # Python libs
  - sudo pip3 install ftputil
  - sudo pip3 install yattag
  # 7zip
  - brew install p7zip
  # Qt
  - brew install qt5
  - brew link --force qt5 # Create the symlinks for Qt
  - qmake -v
  # QtIFW
  - curl -L -O ${QTIFW_URL}
  - hdiutil attach "${QTIFW_BASE}.dmg"
  - ${QTIFW_EXE} --script ${QTIFW_SCRIPT}

#---------------------------------#
#       build configuration       #
#---------------------------------#

#before_script:

script:
  # Build
  - python3 ${SCRIPTS_DIR}/makeQtProFiles.py
  - python3 ${SCRIPTS_DIR}/makeBuild.py ${BRANCH}
  # Tests
  - ${RELEASE_DIR}/${PROJECT_NAME}Console --help
  - ${RELEASE_DIR}/${PROJECT_NAME}Tests
  # Deployment
  - python3 ${SCRIPTS_DIR}/makeDeploy.py
  # Installer
  - python3 ${SCRIPTS_DIR}/makeInstaller.py
  # Artifacts
  - "7z a -tzip -bso0 -bsp0 ${INSTALLER_ZIP} ${INSTALLER_EXE}"

#---------------------------------#
#      upload configuration       #
#---------------------------------#

after_success:
  - python3 ${SCRIPTS_DIR}/upload.py ${FTP_DOMAIN} ${FTP_USER} ${FTP_PASSWORD} ${REPO} ${FTP_REPOS_DIR};
  - python3 ${SCRIPTS_DIR}/upload.py ${FTP_DOMAIN} ${FTP_USER} ${FTP_PASSWORD} ${INSTALLER_ZIP} ${FTP_RELEASES_DIR}/${LATEST_RELEASE_NAME};
