#---------------------------------#
#      general configuration      #
#---------------------------------#

os: linuxXXX
#dist: precise # Ubuntu 12.04, https://docs.travis-ci.com/user/reference/overview/
dist: trusty # Ubuntu 14.04, https://docs.travis-ci.com/user/reference/overview/
sudo: required
#group: deprecated-2017Q4 # https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch

compiler: gcc

language: cpp

branches:
  only:
  - linux_gcc

#---------------------------------#
#    environment configuration    #
#---------------------------------#

env:
  # Global variables
  global:
    # FTP_DOMAIN
    - secure: "tYxdTxP7Pm5ubhqgoMcBAk0yaq0V9RtpB+C045F814Mp2g9ERRUfChDKCbrwaCewgQNJBPaWKbBetnEIyNNCWfMsL3jLQrzQ4NVkg0yb7lTiBdlrIea3R6I7QMT6V2aK/wHPPCxY3PoStJ+V8OxZs6mD3OoblZo8GgnHTHIjEdaZWIo5Ay5GNqQk7M6BYFS92uVQ+QB7sM9ukGs5dL0hxHZVmiQKeAM6VayWPQjkcgMRa72E7r1wXWr3tpFuUMcCSkoJVDXEDNshc+Jxo40cHNZP7nGTuFXD5yvI48FYJ5W29ghc5Zw+0YQKdbtSWYvaWP6kblq0fXtJWKksS+xOP+1JLB1+H6R+ZNFAcd0tzmQhMvAMn1lBaRKzebXiMAgOAHZ594MqCml6N90uihyHJqWQUHKzgutVM5DJRrwdDtDRZWuWhgGVdcRcD+d93MxHJX28YmqMSZMtiZmvD0t/qRqsJZNBlB8uiaFHaZW3gZmPjsbAX4YEris3fHCtSVORMex2LPJSZ3/HEhy4ZLwvC5dAtcQzVv09KU2RX38VNN7Xx1oYbbKMnvMeIRa5TBBwFCRilrH9wAvoNHS7AOUNIRG0gQW37zVhQx8s1Mw/4zhSPdRnQvHrv5NGkETQimTEhFs+v6jtLY1ZGx7IXC2xTdAfEVa/YRXLY0sTXTcCg+o="
    # FTP_USER
    - secure: "MH5Wpl/13VVONs9uWRXaK/3fJx6ndZ4Z+ROsNBYcOSbaAKNo5ZgGNSroLIFMOFMcfKxsYwxeA6wG2sQn77guF2V0hpGi4AcQRKXBzbHpoJ+AyD5XnJPMeGIMP1hSxCbVpQPBSYiOomgxDiHJPu9rcOMa6ODmNpPNZdAZQP3DWCwF1TSb7XFxOpU0PHCnMS7KB+AhyRq4N30d+8TJmrkf6A4d+74p98WmEtJdqRub7iI54Xmdnet1i7KRaeUNAGVmq+sppjySwT+jpTy1SN6YsX5BrvvYv0sOljO5lp9HlhiTKFX4BNYJJIzUOjvjAQ5CqCBc2K50SrvhM004s3QdRAXB4Ku6nQ8zdefsD/QG0GQdt0isagnoYcBP3FOOZJhtV13eEkOuC6q+oiyHcJucfrQCrrw2/xby2rpJR3NdIChyodCPMFHNJhHZUuCHnrtNBrIBrvfG9aF4uZtRM+fWUgn9Dh3eM+iYGjJWI1L72l0nNWqwPHiTAT29CL0GkiazId9bQVvDuOodabyhKMdUAhSIbXCk/NrRGLvvA7/5svnVtlf3s5qdsw41jBNbbYwYZ8hw2e2ybIui9DnyXydj/VuEPAYalqlQxI6o+2qHyLTLfhiuB9R8jLJ8xwdI0lESpzZCn/+yn/6qID4xBERqFpiGirOhNbDM1yvu8WLO2tc="
    # FTP_PASSWORD
    - secure: "kZ+TL5AdG4IsYqBRqsMsDx0rY8+b5P0GqvKavt36mF0UCgI14QT7X19aolPXQvsmAzxN0jdDPXEme+vXwzCGwoaSGxe57A0tO6KhzGmMzyE6JPvS8TTbG/EWkr770gVup8dWufoDlgTu3D6TkPPtvPOSExjBhb9XFvNThDMGrk6vpR27CNJPPEonpYUAAG2hTUOcCYoPhwKFRqQLG/toKAj2AgwUteT3G6qkBdLZQCMMK7mrIjmMurmUIFDnrQJQ3hSpyC6dumF/t5RKKqYHc2lBjI9ReVgB+qTTlGjHK3NFXk5Jf0hr/LXiIBZb1rKPNpoVZHCRvBS42vM9/Ywj0kH2E8E5bhBogXLFy+Ch1oxczlyFNdoPsQlThR80bu47bDXU92431yL2NdF87Om7u2SI++vRiIMk/zofbjGn5D2i6t6aCo15eV1VITQ2oLPwtKtQWLBGTR6aSBYZEtQf6tfhYOnSMlHUZEZX8M9cLrbK5pl8VmK47PEts8S9JPJcjm+aiOjl9GX0Bnj/QaDsYj3fDIjn/cyBMeGqYxws9ISdBUpG7LeNCJLPFSpCuPXPj3pg65+5/pBTXzueVuq71TWRLaMmpYhCMtacs0Lb9jKYgPYZHANkBY46SfWVvJD2COpoRwq1BSjuOGU8d8R9AC60OTb3vd9R/yJxHvrLNj0="
  # Build matrix
  matrix:
    - CONFIGURATION=release
    #- CONFIGURATION=debug

#---------------------------------#
#      install configuration      #
#---------------------------------#

before_install:
  # Set variables
  - export BUILD_TYPE="$(tr '[:lower:]' '[:upper:]' <<< ${CONFIGURATION:0:1})${CONFIGURATION:1}"
  # Project
  - export PROJECT_NAME=$(basename ${TRAVIS_REPO_SLUG})
  #- git describe --abbrev=0 --tags
  #- export LATEST_RELEASE_NAME=$(git for-each-ref refs/tags --sort=-taggerdate --format='%(refname:short)' --count=1)
  #- export LATEST_RELEASE_NAME=$(git describe --tags $(git rev-list --tags --max-count=1))
  #- export LATEST_RELEASE_NAME=$(git describe --tags --abbrev=0 --match v*.*.*)
  #- export LATEST_RELEASE_NAME=$(git describe --tags $(git rev-list --tags='v[0-9].[0-9]*' --max-count=1))
  - git fetch -t
  - export LATEST_RELEASE_NAME=$(git tag -l v[0-9].* | tail -n1)
  - export SCRIPTS_DIR=${TRAVIS_BUILD_DIR}/Scripts
  - export RELEASE_DIR=${TRAVIS_BUILD_DIR}/../Build/${BUILD_TYPE}
  # Deploy
  - export DEPLOY_DIR=${RELEASE_DIR}/../Deploy
  - export LINUXDEPLOYQT_URL="https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - export LINUXDEPLOYQT_EXE=linuxdeployqt
  - export PATH=$PATH:${TRAVIS_BUILD_DIR}
  # QtIFW
  - export QTIFW_VERSION="3.0.4"
  - export QTIFW_BASE="QtInstallerFramework-linux-x64"
  - export QTIFW_EXE="${QTIFW_BASE}.run"
  - export QTIFW_URL="https://download.qt.io/official_releases/qt-installer-framework/${QTIFW_VERSION}/${QTIFW_EXE}"
  - export QTIFW_SCRIPT="${TRAVIS_BUILD_DIR}/Scripts/silentinstall.js"
  - export PATH=$PATH:~/Qt/QtIFW-${QTIFW_VERSION}/bin
  # Installer
  - export INSTALLER_DIR=${RELEASE_DIR}/../Installer
  - export INSTALLER=${INSTALLER_DIR}/${PROJECT_NAME}Installer
  - export INSTALLER_EXE=${INSTALLER}
  - export INSTALLER_ZIP=${INSTALLER}-linux64.zip
  # Upload
  - export REPO=${INSTALLER_DIR}/${TRAVIS_BRANCH}
  - export FTP_RELEASES_DIR=releases
  - export FTP_REPOS_DIR=repositories/${TRAVIS_BRANCH}
  # Print variables
  - echo ${CONFIGURATION}
  - echo ${BUILD_TYPE}
  - echo ${TRAVIS_BUILD_DIR}
  - echo ${PROJECT_NAME}
  - echo ${LATEST_RELEASE_NAME}
  - echo ${RELEASE_DIR}
  - echo ${SCRIPTS_DIR}
  - echo ${TRAVIS_BRANCH}
  # Add repositories, update...
  - sudo apt-add-repository --yes ppa:beineri/opt-qt593-trusty
  - sudo add-apt-repository --yes ppa:jonathonf/python-3.6
  #- sudo add-apt-repository --yes ppa:deadsnakes/ppa
  - sudo apt-get --quiet --yes update
  #- sudo apt-get -qq update

# Install Python, Pip, Qt, QtIFW, etc.
install:
  # Python
  - sudo apt-get --yes install python3.6
  - sudo ln -s /usr/bin/python3.6 /usr/local/bin/python3
  #- sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1
  - python3 --version
  # Pip
  - wget https://bootstrap.pypa.io/get-pip.py
  - sudo python3 get-pip.py
  #- curl https://bootstrap.pypa.io/get-pip.py | sudo python3.6
  - pip3 --version
  # Misc
  - sudo pip3 install yattag
  - sudo pip3 install ftputil
  # Qt
  - sudo apt-get --yes install qt59base qt59svg
  #- sudo apt-get --yes install qt59base qt59svg qt59translations qt59webengine
  # 7zip
  - sudo apt-get --yes install p7zip-full
  # QtIFW
  - curl -L ${QTIFW_URL} -O
  - chmod a+x ${QTIFW_EXE}
  - QT_QPA_PLATFORM=minimal ${QTIFW_EXE} --script ${QTIFW_SCRIPT} --no-force-installations

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_script:
  - source /opt/qt*/bin/qt*-env.sh
  - qmake -v

script:
  # Build
  - python3 ${SCRIPTS_DIR}/makeQtProFiles.py
  - python3 ${SCRIPTS_DIR}/makeBuild.py ${TRAVIS_BRANCH}
  # Tests
  - ${RELEASE_DIR}/${PROJECT_NAME}Console --help
  - ${RELEASE_DIR}/${PROJECT_NAME}Tests
  # Deployment, https://github.com/probonopd/linuxdeployqt
  - curl -L ${LINUXDEPLOYQT_URL} -o ${LINUXDEPLOYQT_EXE}
  - chmod a+x ${LINUXDEPLOYQT_EXE}
  - unset QTDIR; unset QT_PLUGIN_PATH; unset LD_LIBRARY_PATH
  - python3 ${SCRIPTS_DIR}/makeDeploy.py
  # Installer
  - python3 ${SCRIPTS_DIR}/makeInstaller.py ${TRAVIS_BRANCH}
  # Artifacts
  - 7z a -tzip ${INSTALLER_ZIP} ${INSTALLER_EXE}

#---------------------------------#
#      upload configuration       #
#---------------------------------#
#after_success:
#  - python3 ${SCRIPTS_DIR}/upload.py ${FTP_DOMAIN} ${FTP_USER} ${FTP_PASSWORD} ${REPO} ${FTP_REPOS_DIR}
#  - python3 ${SCRIPTS_DIR}/upload.py ${FTP_DOMAIN} ${FTP_USER} ${FTP_PASSWORD} ${INSTALLER_ZIP} ${FTP_RELEASES_DIR}/${LATEST_RELEASE_NAME}
