#---------------------------------#
#      general configuration      #
#---------------------------------#

# Ubuntu 14.04, https://docs.travis-ci.com/user/reference/overview/
os: linux
dist: trusty
sudo: required

compiler: gcc

language: cpp

branches:
  only:
  - linux_gcc

#---------------------------------#
#    environment configuration    #
#---------------------------------#

env:
  # Global variables
  global:
    # ftp user name, password
    - secure: "kyKbOs5ELlY35uavuWhw5EZNxMdAPv4Y0PWFFTMb907Q7r2SPfE6fNIxIRJcYqfpbZWxG3zNqbzsAFzkcPii64MqF+1hgULRHVanyuaUMT5FLvQ8nvHO0WW0Pil4yrqmOkiKMd1lJkizl/7g9jI9+ZHYGjdFsMeJAm5gaW1F8mjenVL7Hfi1IbPZm+NlVLHq2hFULL+SGQlzo2Nq2BAovqbf0y6ntZmnlWywadV1sfLYSB2ebEDE1u+Aro888FLV8qQwyj026wvLNP9QtdBgT0tnGIMw2g/3M7jJDJ51jUIQ93W4iKCFnjQTx0ttgFh1VIa9sC+SOMDH33ep5BXykQRCrvhCBLzkDet02r84bwZ1V7y4LWqN3q9kZ+gnj0/IsoyopfC8bZrvMuy/3NTAcbmm5BHK9DbeKN58ooD5Jaq7tadHxUY/7uymF3XQa0KSL+w3AOigZsvPUb1AP7+fnvETBERCQjxZp5SiGhgABFnv43HhlMUg9xkDT3WhUdht+hJ+rzpLm/A0LEMk3ytOkaKIvikMBZ3XlL07JsVG2baHKPovBfoSqSI9E2f6clE9CqR6IkJFvqqcrPrbcB+vv5n7gZ2wQn580aMoCF9UmxkNQHokN13GYuYAIxeAdsOLjEypgsimYA67MUCY28VACzuHWzWmT9zEECw52oAtSyE="
    - secure: "iHdoJjqfYRURWbVxDcM9I2y4JNMVlc7fKn+V1iFjmLfotkcEQoWdLfCiXI44vY9vKEMTylHEMcIru+VAsC/ZZGzUgnP3BZ722PGCWzEUntHXcvajku8Ef2r5tItD4TZHnG/A/VHAaZYLKoMRbm52+uzlVrQGEHxioG5nYy1Dx7N/arlw1sZeDh4zNEncZOkmoGK+F8zA+HhSWraTeeMEoVnsksJTowHFRWsGm/eNDx6ojhszHmlz3T37Zog4fjs8TWyFOjAgQw1fNiBldiPwNigiZqj4nd4wC9rpt475JIAfGzBtsduINud9mTpA+Uam75KQ2G6vsnhPzgUiUXDQJr6WCO8iYUJQfaRx9j08czEr3qEmmyUglXJP0u9H6Syw48KB2GCUiwRk7vp8OpZsGgZ2/V3inlCQlKEEAGuBGD8J6ctFjvwyqRJxdxnXXv6ow5xU7E4kRJDWWtyzIBE1nUbL42XLtbISioMWgfjSamDMU7t3I8F8G9K3uOe2OKNlLipklP/5pGNvCquF7nE7vU7V9280Un626kY5k+Alkr3PhnVHTMcEoZ3vk947rHV95gWHHsYdUqRofGwyguBCc6pyoh7fsJ/iMEEjtWNOiRnUPv4e6lcc82diB9PUpVdD18syhuSxrWsbvtOtqUvz1Iy9geyN/07NQfotpPMRrRA="
  # Build matrix
  matrix:
    - CONFIGURATION=release
    #- CONFIGURATION=debug

#---------------------------------#
#      install configuration      #
#---------------------------------#

before_install:
  # Set variables
  - export BUILD_TYPE="$(tr '[:lower:]' '[:upper:]' <<< ${CONFIGURATION:0:1})${CONFIGURATION:1}"
  # Project
  - export PROJECT_NAME=$(basename ${TRAVIS_REPO_SLUG})
  - export LATEST_RELEASE_NAME=$(git describe --tags --abbrev=0 --match v*.*.*)
  - export SCRIPTS_DIR=${TRAVIS_BUILD_DIR}/Scripts
  - export RELEASE_DIR=${TRAVIS_BUILD_DIR}/../Build/${BUILD_TYPE}
  # Deploy
  - export DEPLOY_DIR=${RELEASE_DIR}/../Deploy
  - export LINUXDEPLOYQT_URL="https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - export LINUXDEPLOYQT_EXE=linuxdeployqt
  - export PATH=$PATH:${TRAVIS_BUILD_DIR}
  # QtIFW
  - export QTIFW_VERSION="3.0.2"
  - export QTIFW_BASE="QtInstallerFramework-linux-x64"
  - export QTIFW_EXE="${QTIFW_BASE}.run"
  - export QTIFW_URL="https://download.qt.io/official_releases/qt-installer-framework/${QTIFW_VERSION}/${QTIFW_EXE}"
  - export QTIFW_SCRIPT="${TRAVIS_BUILD_DIR}/Scripts/silentinstall.js"
  - export PATH=$PATH:~/Qt/QtIFW-${QTIFW_VERSION}/bin
  # Installer
  - export INSTALLER_DIR=${RELEASE_DIR}/../Installer
  - export INSTALLER=${INSTALLER_DIR}/${PROJECT_NAME}Installer
  - export INSTALLER_EXE=${INSTALLER}
  - export INSTALLER_ZIP=${INSTALLER}-linux64.zip
  # Upload
  - export REPO=${INSTALLER_DIR}/${TRAVIS_BRANCH}
  - export FTP_DOMAIN=sazonov.org
  - export FTP_RELEASES_DIR=davinci.sazonov.org/releases
  - export FTP_REPOS_DIR=davinci.sazonov.org/repositories/${TRAVIS_BRANCH}
  # Print variables
  - echo ${CONFIGURATION}
  - echo ${BUILD_TYPE}
  - echo ${TRAVIS_BUILD_DIR}
  - echo ${PROJECT_NAME}
  - echo ${LATEST_RELEASE_NAME}
  - echo ${RELEASE_DIR}
  - echo ${SCRIPTS_DIR}
  # Add repositories, update...
  - sudo add-apt-repository --yes ppa:jonathonf/python-3.6
  #- sudo add-apt-repository --yes ppa:deadsnakes/ppa
  - sudo apt-add-repository --yes ppa:beineri/opt-qt592-trusty
  - sudo apt-get -qq update

# Install Python, Pip, Qt, QtIFW
install:
  - sudo apt-get --yes install python3.6
  - curl https://bootstrap.pypa.io/get-pip.py | sudo python3.6
  #- sudo rm /usr/bin/python3
  #- sudo ln -s /usr/bin/python3.6 /usr/bin/python3 doesn't really help when run python3
  - sudo pip3 install yattag
  - sudo pip3 install ftputil
  #- sudo apt-get --yes install qt59base qt59svg qt59translations qt59webengine
  - sudo apt-get --yes install qt59base qt59svg
  - sudo apt-get --yes install p7zip-full
  - curl -L ${QTIFW_URL} -O
  - chmod a+x ${QTIFW_EXE}
  - QT_QPA_PLATFORM=minimal ${QTIFW_EXE} --script ${QTIFW_SCRIPT} --no-force-installations
  - echo ${LATEST_RELEASE_NAME}
  - export LATEST_RELEASE_NAME=$(git describe --tags --abbrev=0 --match v*.*.*)
  - echo ${LATEST_RELEASE_NAME}

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_script:
  - source /opt/qt*/bin/qt*-env.sh

script:
  # Build
  - python3.6 ${SCRIPTS_DIR}/makeQtProFiles.py
  - python3.6 ${SCRIPTS_DIR}/makeBuild.py ${TRAVIS_BRANCH}
  - ls ${RELEASE_DIR}
  # Tests
  - ${RELEASE_DIR}/${PROJECT_NAME}Console --help
  - ${RELEASE_DIR}/${PROJECT_NAME}Tests
  # Deployment, https://github.com/probonopd/linuxdeployqt
  - curl -L ${LINUXDEPLOYQT_URL} -o ${LINUXDEPLOYQT_EXE}
  - chmod a+x ${LINUXDEPLOYQT_EXE}
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - python3.6 ${SCRIPTS_DIR}/makeDeploy.py
  - ls ${DEPLOY_DIR}
  # Installer
  - python3.6 ${SCRIPTS_DIR}/makeInstaller.py ${TRAVIS_BRANCH}
  - ls ${INSTALLER_DIR}
  - 7z a -tzip ${INSTALLER_ZIP} ${INSTALLER_EXE}

#---------------------------------#
#      upload configuration       #
#---------------------------------#
after_success:
  - python3.6 ${SCRIPTS_DIR}/upload.py ${FTP_DOMAIN} ${FTP_USER} ${FTP_PASSWORD} ${REPO} ${FTP_REPOS_DIR};
  - python3.6 ${SCRIPTS_DIR}/upload.py ${FTP_DOMAIN} ${FTP_USER} ${FTP_PASSWORD} ${INSTALLER_ZIP} ${FTP_RELEASES_DIR}/${LATEST_RELEASE_NAME};
